services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=optic_data
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  java_app:
    container_name: java_app
    image: jdpalmares/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://localhost:3306/optic_data?useSSL=false
      - DATABASE_USERNAME=spring
      - DATABASE_PASSWORD=spring
    depends_on:
      - mysqldb
      
volumes:
  db: