services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=optic_data
    networks:
      - bot-network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  java_app:
    container_name: java_app
    image: app:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/optic_data?useSSL=false
      - DATABASE_USERNAME=spring
      - DATABASE_PASSWORD=spring
      - DATABASE_DIALECT=org.hibernate.dialect.MySQLDialect
    networks:
      - bot-network

volumes:
  db:

networks:
  bot-network:
    driver: bridge