services:

  java_app:
    container_name: java_app
    image: jdpalmares/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/optic_data?useSSL=false",
        "spring.datasource.username" : "spring",
        "spring.datasource.password" : "spring",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name=com.mysql.jdbc.Driver" : "com.mysql.jdbc.Driver" }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=optic_data
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d